// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

// Import the Verifier contract generated by ZoKrates
import "./verifier.sol";

contract ScholarPi_PiQ_Token {
    string public name = "Pi Quotient";
    string public symbol = "piQ";
    uint8 public decimals = 18;
    
    address public admin;
    uint256 public totalSupply;
    mapping(address => uint256) public balanceOf;
    mapping(string => bool) public hasBeenAssessed;

    // Reference to the ZoKrates Verifier
    Verifier public zkVerifier;

    event Mint(address indexed researcher, uint256 amount, string evalHash);
    
    modifier onlyAdmin() {
        require(msg.sender == admin, "Unauthorized");
        _;
    }

    // Pass the deployed address of verifier.sol to the constructor
    constructor(address _verifierAddress) {
        admin = msg.sender;
        zkVerifier = Verifier(_verifierAddress);
    }

    /**
     * @dev Mints piQ to researcher using a true zk-SNARK Groth16 proof.
     */
    function verifyProofAndMint(
        address researcher, 
        uint256 amountWei, 
        string memory evalHash,
        uint256 truncatedHashInt, // The public input bound to the proof
        Verifier.Proof memory proof // The a, b, and c structs from proof.json
    ) public onlyAdmin {
        
        require(!hasBeenAssessed[evalHash], "Fraud Detected: Manuscript already assessed.");
        require(amountWei > 0, "Mint amount must be > 0.");

        // 1. Prepare the public input array for the Verifier 
        // (ZoKrates requires inputs as a uint256 array)
        uint256[1] memory publicInputs = [truncatedHashInt];

        // 2. Execute the native zk-SNARK verification
        bool isValid = zkVerifier.verifyTx(proof, publicInputs);
        require(isValid, "ZK-SNARK Proof Verification Failed! Parameters do not meet the circuit logic.");

        // 3. Effect the mint
        hasBeenAssessed[evalHash] = true;
        balanceOf[researcher] += amountWei;
        totalSupply += amountWei;

        emit Mint(researcher, amountWei, evalHash);
    }
}
